### ISSUE TITLE
Tablet View - 'Save the date' breaks the styling

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#216]
Tested on IPAD AIR 2 on Safari with browsrstack

<img width="426" alt="screen shot 2016-09-01 at 12 01 36" src="https://cloud.githubusercontent.com/assets/16544365/18165245/151dabf6-703c-11e6-8db9-1415ec18b354.png">

#### to repro
1. Go to https://staging.react.london/

**Comment by zoeabryant** [comment]
This problem is because flexbox is not working. Flexbox is only supported by (iOS version 9.2^)[http://caniuse.com/#feat=flexbox] - BrowserStack IPad Air 2 uses iOS version 8.

iOS version 9 was released almost a year ago - (September 16, 2015)[https://en.wikipedia.org/wiki/IOS_9]. We should check the google analytics to see how many users this affects - flexbox not working affects many other parts of the site.
