### ISSUE TITLE
Design review - static site

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/react.london#67]
BANNER 
- [x] fix grid in the centre (low priority)
- [x] Grid background image doesn't work with inline SVG on some firefox (need to extract into image file or URI encode svg)

NAV
- [x] conference page #E9F2F6 background
- [x] Mobile view: too high

ABOUT
- [x] Mobile version: 22px 0px;
- [x] Tablet version: 30px 0px;
- [x] Small text version: gap between p's = 12px

- [x] LINE DASHES - more control

NEXT EVENT - SAVE THE DATE
- [x] padding-right: 35px;
- [x] content: To get reminders about tickets & future events subscribe here
- [x] __header { margin-bottom: 5px; }
- [x] subheadings {     margin-top: 16px; }

STAY TUNED
- [x] centered like conf page
- [x] solid line between stay tuned / slack
- [x] Subscribe not 'submit'
- [x] button should be bold text

JOIN SLACK
- [x] spacing bottom = 20px
- [x] styling:
.JoinTheConversation .JoinTheConversation__btn {
    border-radius: 6px;
    /* text-transform: uppercase; */
    border: 0px;
    padding: 12px 15px;
    color: #CDE5B3;
    font-weight: bold;
    background: #D2090B;
    text-decoration: none;
    font-size: 20px;
    background: url("../../../../assets/img/PNG/Slack.png") no-repeat 10px 14px #4A4A4A;

FOOTER
- [x] Twitter icon - don't override speaker twitter icon

CONF
- [x] matches STAY TUNED

**Comment by zoeabryant** [comment]
- [ ] updating nav bar to reflect design (conf & community) page

- [ ] updating paragraph text - conference page

- [ ] updating paragraph text size - match conf & community. (community is the right size)

- [ ] header area update new graphic (conf page)

- [ ]

**Comment by AndrewBestbier** [comment]
- [] Check if anchor tags still work

**Comment by zoeabryant** [comment]
- [ ] **Cross browser testing**

**Comment by zoeabryant** [comment]
**CROSS BROWSER TESTING**
- [ ] text on banner doesn't use the uploaded font

**Comment by lpil** [comment]
- [x] Page extends out of viewport on narrower screens

**Comment by AndrewBestbier** [comment]
Speakers:
- [ ] Remove unused links
- [ ] Open links in new tab

Next Event:
- [ ] Location pin fraction down few pixels

Footer:
- [ ] Slack and Twitter logo not working on hover
- [ ] Ensure Youtube has correct link to playlist of meetups
- [ ] Change text to watch previous meetups 
- [ ] Red badger logo links to Red bagder website

General:
- [ ] webkit fix prefix on flexbox stuff (ask zoe later)
- [ ] Accessibility focus, skips out middle section

Hero
- [ ] Community text taken out in hero title

MailChimp:
- [ ]  Update the image (Mail_React_White)

Next Event:
- [ ] and instead of &

Conference:
- [ ] Sign up here for conference updates (add conference)

Conference Link:
- [ ] 2017 changes to conference

**Comment by AndrewBestbier** [comment]
Andrew:
- [ ] Bens github link needs to be added -> see slack -> https://github.com/benjdlambert
- [ ] Check why google asks us to robot form still!
- [ ] Anchor link on conference page works

Blocked:
- [ ] Logo in footer needs to be moved down a bit - 

Zoe:
- [ ] Revert to color
- [ ] Next event details are cramped together in Safari
- [ ] Footer is in one column in safari

Todo:
- [ ] Powered by red badger is not centered in the red band

Known but leaving:
- [ ] Chrome on iPhone if click on link and navigate back, the icon stays in the hover state
